### ISSUE TITLE
fields are missing on update dataset and are gone after submit edit form dataset

### ISSUE THREAD

**Issue by JihadMotii-REISys** [ngds/ckanext-metadata#16]
When you create a dataset using USGIN structure and providing (content model, content model version and content layer) then you edit this dataset, those fields won't be shown and if you submit the edit form, the USGIN Structure fields values are gone.

Is this a normal behavior ?

**Comment by smrazgs** [comment]
same as https://github.com/ngds/ckanext-ngds/issues/635

**Comment by GaryHudmanAZGS** [comment]
metatdata editor - action package_create and plugin schema_modify modified to correctly handle editor json.  All fields appearing
