### ISSUE TITLE
update usginmodels to 1.1.6

### ISSUE THREAD

**Issue by jessica-azgs** [ngds/ckanext-metadata#20]
@JihadMotii-REISys @FuhuXia usginmodels was updated so a file does not pass validation if there are field names with extra whitespace. Problem discovered in https://github.com/ngds/ckanext-geoserver/issues/7

**Comment by ccaudill** [comment]
https://github.com/REI-Systems/ckanext-metadata/commit/1d09f633e1d65f0e8dfd82ad86039d4c96bb5788
