### ISSUE TITLE
usgin content model keywords gettting truncated in harvest

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-metadata#21]
looks like getting clipped to 50 characters. Did a little research and don't see anywhere that keyword text is limited in length. I'd suggest starting with ckanext-metadata/ckanext/harvest/usgin.py: get_package_dict, which starts the process of building CKAN package from harvested xml. 

also possible that its something in the pyCSW loading and indexing...  The clipped keyword shows up in csw xml responses
@Lbookman @GaryHudmanAZGS

**Comment by GaryHudmanAZGS** [comment]
truncation was occurring in the ckanext-spatial/harvester/base.py get_package_dict. Truncated to 50 even thought the database field is 100.  Corrected in test.

**Comment by GaryHudmanAZGS** [comment]
This has also been corrected in production server.  Haven't seen the problem since the change,  any other instances of this coming up ? Otherwise this seems fixed
