### ISSUE TITLE
PDF preview not working

### ISSUE THREAD

**Issue by Lbookman** [ngds/ckanext-metadata#22]
PDFs don't show in ckan pdf preview. needs to be updated. @GaryHudmanAZGS 

http://search.geothermaldata.org/dataset/newberry-well-55-29-stimulation-data-cladouhos-newberry-meq-sgws-2013-pdf/resource/edb18ee3-36d0-4b59-abc1-2ce7d9fd2fd5

**Comment by GaryHudmanAZGS** [comment]
Changed from 1Mb to 50 MB max file size in the resourceproxy config.  Does this fix what you were seeing ?

**Comment by Lbookman** [comment]
yes. that fixed the problem.

**Comment by GaryHudmanAZGS** [comment]
So you add a new connection with the following parameters

production

10.208.3.104
port 5432
user: ckan_default

test
10.208.30.122
port 5432

password is the same for both its keypass

Gary
