### ISSUE TITLE
Duplicates in catalog

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-metadata#23]
http://search.geothermaldata.org/dataset/alabama-geothermal-resource-references (newest)
http://search.geothermaldata.org/dataset/alabama-geothermal-resource-references7a7e5
http://search.geothermaldata.org/dataset/alabama-geothermal-resource-references6fc8a
http://search.geothermaldata.org/dataset/alabama-geothermal-resource-references4826f

all seem to be about same resource. (original guid 6653d470c471cd6f30088b387020ca81)

the most recent one displays differently, has different content.  why do we have 4 copies and why is the newest different?

**Comment by smrazgs** [comment]
this is a different problem than the multiple records we're getting from NREL

**Comment by GaryHudmanAZGS** [comment]
These records have identical guids and have 2 harvest sources. The harvest process only checks guids for the current harvest source. Also noted that there were harvest errors that may have contributed to the duplication. I have run a clean up script that de-activates the errors, and only one now appears in the search.  Gary

**Comment by GaryHudmanAZGS** [comment]
Harvest fixes now eliminate duplicate guids, fixes in gather, fetch and import are now in production system.
